### ISSUE TITLE
Does the code use the same hyper parameters as the paper described?

### ISSUE THREAD

**Issue by ssssholmes** [NVlabs/DiscoBox#1]
Thanks for great work!

I read the code in MeanField class. It seems that it is inconsistent with the paper.

<img width="376" alt="屏幕快照 2021-10-24 15 18 19" src="https://user-images.githubusercontent.com/48430696/138584564-b916fb2a-2006-41e1-8240-064a5a93e1c0.png">

 
https://github.com/NVlabs/DiscoBox/blob/3b170414c330ca6a41af56bfaad36313383d702c/mmdet/models/dense_heads/discobox_solov2_head.py#L744-L814

**Comment by ssssholmes** [comment]
So I may have a few questions:

1. why does the feature_map need to add 10 in the codebase in line 760?
2. "targets" in forward function seems to be generated from gt_masks, does it mean that discobox still needs gt_mask as supervision signal.
3. "x" in forward function seems not to be a roi feature cropped from feature map.

**Comment by voidrank** [comment]
Hi @ssssholmes,

Thank you for your interests in our work. We are pleased to answer your questions:

1. +10 is only a trick to better isolate padded pixels from the real pixels inside the image. It does not directly change the mean field inference on real pixels as adding 10 does not change the difference value in kernel computation. We apply pairwise potential in a convolution-like manner, thus we need to pad some pixels outside the image border. The RGB values of those padded pixels are set to be 0 by default. We add 10 on each real pixel to enlarge their difference from the padded pixels, so that the padded pixels affect less on the real pixels.

2. `gt_masks` actually refers to treating the boxes as foreground masks. It's a naming problem and we will change it. Sorry for the confusion. To be more specific, if the output mask size if H x W, the gt_masks is defineds as a binary matrix G of H x W. `gt_masks_{i,j} = 1` if the pixel (i, j) is inside the bounding box of the target object. `gt_masks_{i,j} = 0` if pixel (i, j) is outside the bounding box.

3. You are right. In the paper we consider both YOLACT and SOLOv2 and there are subtle differences in their code bases. Our description in the paper mainly follows YOLACT which takes in cropped RoI features. On SOLOv2, we mostly follow their original implementation to take in the whole feature map. This is to keep the codebase clean and close to the original implementation. However, it should be mentioned that we do use bounding boxes as a mask to restrict the losses, mean field inference, and correspondence computation happening only inside the boxes. Thus everything is still on the RoI level.

**Comment by ssssholmes** [comment]
@voidrank Got it! Thank you!
